/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import lombok.Data;

public class App {
  public String getGreeting() {
    return "Hello World!";
  }

  public static void main(String[] args) {
    System.out.println(new App().getGreeting());
  }

  @Data
  static class Some {

  }
}
