
version: '3.8'

services:

  app:
    image: fizlrock/seabattle-api:latest       # Образ вашего сервиса
    container_name: seabattle_api
    environment:
      DB_HOST: localhost # Имя сервиса базы данных из docker-compose
      DB_PORT: 5432                    # Порт БД
      DB_NAME: seabattle_db
      DB_USER: service
      DB_PASSWORD: password
    ports:
      - "1234:8080"                    
    depends_on:
      - postgres                       
