
services:

  app:
    image: fizlrock/seabattle-api:latest       
    container_name: seabattle_api
    environment:
      DB_HOST: database
      DB_PORT: 5432                    
      DB_NAME: seabattle_db
      DB_USER: service
      DB_PASSWORD: password

    command:
     - "--spring.profiles.active=production"        
    ports:
      - "1234:80"                    
    depends_on:
      - database                      
    networks:
      - app_network

      
  database:
    image: postgres:latest
    container_name: seabattle_database
    restart: always
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: password
      POSTGRES_DB: seabattle_db
    ports:
      - "532:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  postgres_data:


networks:
  app_network:
    driver: bridge
