
server:
  port: 80

seabattle:
  # Таймаут вебхука. Через сколько завершается подключение
  webhook_timeout: 10

  # Таймаут матчмейкинга
  matchmaking_timeout: 120

  # Таймаут на ход игрока
  fire_timeout: 120


  # Период проверки пула игр. На завершенные для сохранения, на failed для удаления
  pool_check_period: 20

  
spring:
  web:
    charset: UTF-8
  r2dbc:
    url: r2dbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

liquibase:
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  enable: true
  change-log: db/changelog.yaml

jpa:
  hibernate:
    ddl-auto: validate

jwt:
  secret: B9+AWyF3OPMqs1PD6FSwj1LArLI63a3CehziWrOgYGk=
  experation: 36000
  issuer: seabattle_service
