/*
 * This source file was generated by the Gradle 'init' task
 */
package org.ssau.seabattle;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.ComponentScan;

@SpringBootApplication
@ComponentScan
public class App {

  public static void main(String[] args) {
    var context = SpringApplication.run(App.class);
    // var filters = context.getBeansOfType(Filter.class);
    // filters.entrySet().stream().forEach(System.out::println);
  }

}
