
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/seabattle
    username: admin
    password: gracesecret

jpa:
  hibernate:
    ddl-auto: validate


jwt:
  secret: arst
  experation: 3600
  issuer: seabattle_service
